function promptText(){return["You are FOXI AI Tire Health Check for consumer tire photo screening in Saudi Arabia.","The customer may upload 1 to 4 tires. Analyze every tire independently.","Each tire has three photos: full tire front, 45 degree tread, and sidewall size/DOT close-up.","For every tire, identify tire size, DOT date, tread wear, scratches/cuts, cracks, sidewall bulge, exposed cords, repair evidence, and photo quality.","If the customer reports sidewall bulge, that tire must be red. If more than 3 repairs are reported, that tire must be red.","If DOT manufacturing date is 3 years or more before today, the tire is older in Saudi Arabia. Do not describe it as new. Score must be 5/10 or lower. Older than 5 years must be 3.5/10 or lower.","Return only JSON: {\"tires\":[{\"index\":1,\"score\":0,\"riskLevel\":\"green|yellow|red\",\"detectedSize\":{\"width\":\"\",\"profile\":\"\",\"rim\":\"\",\"raw\":\"\",\"confidence\":0},\"dot\":{\"code\":\"\",\"week\":0,\"year\":0,\"confidence\":0},\"customerSummary\":\"short customer-safe explanation\",\"visibleFindings\":[{\"customerText\":\"short finding\",\"confidence\":0}],\"confidence\":0}]}","Uploaded tire checks: "+JSON.stringify(tires.map((t,i)=>({index:i+1,checks:t.q})))] .join("\\n")}
async function gemini(){let images=[],n=0,total=tires.length*R.length;for(let i=0;i<tires.length;i++)for(let r of R){n++;images.push({tireIndex:i+1,role:r,...await inline(tires[i].files[r],`Preparing photo ${n}/${total}...`)})}busy("AI is reading tire photos...");let res=await fetch("/.netlify/functions/gemini-tire-check",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({prompt:promptText(),images})});return res.ok?await res.json():{}}
function scoreOf(item,set){let s=typeof item.score=="number"?Math.max(0,Math.min(10,item.score)):7,d=parseDot(item.dot&&item.dot.code);if(d){if(d.months>=60)s=Math.min(s,3.5);else if(d.months>=36)s=Math.min(s,5)}let msg="";if(set.q.bulge=="yes"){s=Math.min(s,2.5);msg="Bulge reported. Replace this tire soon and book a free store check."}else if(set.q.repair=="yes"){s=Math.min(s,3.2);msg="More than 3 repairs reported. Free store inspection is strongly recommended."}else if(set.q.leak=="yes"){s=Math.min(s,6.5);msg="Slow air loss reported. Free inspection is recommended before long or high-speed driving."}return{score:s,dot:d,msg}}
function sizeOf(x){let c=+(x&&x.confidence||0),s=parseSize(x&&(x.raw||`${x.width||""}/${x.profile||""} R${x.rim||""}`));return s&&c>=.35?s:null}
function level(s,item,set){if(set.q.bulge=="yes"||set.q.repair=="yes")return"red";if(item.riskLevel=="red")return"red";if(item.riskLevel=="yellow"&&s>=4)return"yellow";return s<4?"red":s<7?"yellow":"green"}
function dotTxt(d){return d?`DOT ${d.code}${d.months>=36?" - older tire":""}`:"DOT not detected"}
function one(t){let f=(Array.isArray(t.findings)?t.findings:[]).find(x=>x&&x.customerText);return t.summary||f&&f.customerText||"AI photo check complete."}
function card(t){let sc=Math.round(t.score*10)/10,act=t.level=="green"?"No replacement now. Check before long trip.":t.level=="yellow"?"Free inspection recommended.":"Replace or inspect ASAP.";return`<div class=card><div class=row><div><b>Tire ${t.index}</b><div>${t.size?`<span class=pill>${t.size.text}</span>`:`<span class="pill pale">Size not detected</span>`}<span class="pill pale">${dotTxt(t.dot)}</span></div></div><span class="badge ${t.level}">${t.level.toUpperCase()} ${sc}/10</span></div><div class=bar style="--s:${sc}"><i class=mark></i></div><div class=nums>${[0,1,2,3,4,5,6,7,8,9,10].map(n=>`<span>${n}</span>`).join("")}</div><p class=copy>${one(t)}</p><p class=copy>${act}</p></div>`}
function normalize(ai){let raw=Array.isArray(ai.tires)?ai.tires:[];let out=tires.map((set,i)=>{let item=raw.find(x=>+x.index==i+1)||raw[i]||{},r=scoreOf(item,set),sz=sizeOf(item.detectedSize);if(sz&&!foundSize)foundSize=sz;let lv=level(r.score,item,set);return{index:i+1,score:r.score,level:lv,size:sz,dot:r.dot,summary:r.msg||item.customerSummary||"",findings:item.visibleFindings||[]}});bookTarget=out.find(x=>x.level!="green")||out[0];return out}
async function runCheck(){let m=missing();if(m){toast(m);busy(m);return}$("start").disabled=true;$("start").textContent="Checking...";busy("Starting AI check...");try{let ai={};try{ai=await gemini()}catch(e){}let out=normalize(ai);$("cards").innerHTML=out.map(card).join("");$("result").classList.add("show");busy("Done.");$("result").scrollIntoView({behavior:"smooth",block:"start"})}finally{$("start").disabled=false;$("start").textContent="Start AI health check"}}

function dotTxt(d){if(!d||!d.code)return"DOT not detected";let wk=+String(d.code).slice(0,2),yy=+String(d.code).slice(2),y=yy<=40?2000+yy:1900+yy,mo=Math.min(12,Math.max(1,Math.round(wk/4.345))),mn=["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"][mo-1]||"",age=Math.floor(d.months/12)+"y "+d.months%12+"m old";return`DOT ${d.code} - Manufactured: ${mn} ${y} (${age})`}

function dotAny(i){let t=JSON.stringify(i||{}),d=parseDot(t),o=i&&i.dot;if(d)return d;if(o&&o.week&&o.year){let wk=+o.week,y=+o.year,mo=Math.min(12,Math.max(1,Math.round(wk/4.345))),n=new Date,c=String(wk).padStart(2,"0")+String(y).slice(-2);return{code:c,year:y,month:mo,months:Math.max(0,(n.getFullYear()-y)*12+n.getMonth()+1-mo)}}return null}function scoreOf(item,set){let s=typeof item.score=="number"?Math.max(0,Math.min(10,item.score)):7,d=dotAny(item),msg="";if(d){if(d.months>=60)s=Math.min(s,3.5);else if(d.months>=36)s=Math.min(s,5)}if(set.q.bulge=="yes"){s=Math.min(s,2.5);msg="Bulge reported. Replace this tire soon and book a free store check."}else if(set.q.repair=="yes"){s=Math.min(s,3.2);msg="More than 3 repairs reported. Free store inspection is strongly recommended."}else if(set.q.leak=="yes"){s=Math.min(s,6.5);msg="Slow air loss reported. Free inspection is recommended before long or high-speed driving."}return{score:s,dot:d,msg}}function promptText(){return["You are FOXI AI Tire Health Check for Saudi Arabia.","Analyze each tire independently from three photos: front, tread, and sidewall size/DOT close-up.","Important: OCR the sidewall DOT. Look for DOT plus a 4 digit week/year code such as 1324, 2422, 5019. Return dot.code as exact 4 digits whenever visible, even at medium confidence.","Return only JSON with tires, score, riskLevel, detectedSize, dot, customerSummary, visibleFindings.","Checks: "+JSON.stringify(tires.map((t,i)=>({index:i+1,checks:t.q})))] .join("\n")}
