const R=["overall","tread","sidewall"],Q=[["bulge","Bulge?"],["leak","Slow air loss?"],["repair","Repaired 3+?"]],tires=[];let foundSize=null,bookTarget=null;const $=id=>document.getElementById(id);
function toast(t){let e=$("toast");e.textContent=t;e.style.display="block";setTimeout(()=>e.style.display="none",4200)}
function busy(t,on=1){$("status").classList.toggle("show",!!on);$("status").querySelector("span").textContent=t}
function tire(){return{id:Date.now()+Math.random(),files:{},pre:{},q:{}}}
function ttl(r){return r=="overall"?"Front":r=="tread"?"Tread":"Size / DOT"}
function hint(r){return r=="overall"?"Photo or gallery":r=="tread"?"Grooves close-up":"Sidewall close-up"}
function icon(r){return r=="overall"?"◎":r=="tread"?"▧":"DOT1324"}
function norm(t){return(t||"").toUpperCase().replaceAll("O","0").replaceAll("Q","0").replaceAll("|","1")}
function parseSize(t){let m=norm(t).match(/([1-3][0-9]{2})\s*[\/\-]?\s*([2-9][0-9])\s*(?:ZR|R)\s*([1-2][0-9])/);if(!m)return null;let w=+m[1],p=+m[2],r=+m[3];return w>=145&&w<=355&&p>=20&&p<=95&&r>=10&&r<=24?{width:""+w,profile:""+p,rim:""+r,text:`${w}/${p} R${r}`}:null}
function parseDot(t){let m=norm(t).match(/([0-5][0-9][0-4][0-9])/);if(!m)return null;let c=m[1],wk=+c.slice(0,2),yy=+c.slice(2);if(wk<1||wk>53)return null;let y=yy<=40?2000+yy:1900+yy,mo=Math.min(12,Math.max(1,Math.round(wk/4.345))),n=new Date;return{code:c,months:Math.max(0,(n.getFullYear()-y)*12+n.getMonth()+1-mo)}}
function render(){let list=$("tireList");list.innerHTML="";tires.forEach((t,i)=>{let d=document.createElement("div");d.className="tire";d.dataset.id=t.id;d.innerHTML=`<div class=top><span>Tire ${i+1}</span>${tires.length>1?`<button class=remove data-rm=${t.id}>Remove</button>`:""}</div><div class=uploads>${R.map(r=>`<label class="up ${t.files[r]?"done":""}"><input type=file accept="image/*" data-id=${t.id} data-role=${r}>${t.pre[r]?`<img src="${t.pre[r]}" alt="">`:""}<span class=ico>${icon(r)}</span><span><b>${ttl(r)}</b><small>${hint(r)}</small></span></label>`).join("")}</div><div class=qs>${Q.map(([k,txt])=>`<div class=q><p>${txt}</p><div class=seg><button data-k=${k} data-v=yes class="${t.q[k]=="yes"?"on":""}">Yes</button><button data-k=${k} data-v=no class="${t.q[k]=="no"?"on":""}">No</button></div></div>`).join("")}</div>`;list.appendChild(d)});$("addTire").style.display=tires.length>=4?"none":"block";list.querySelectorAll("[data-rm]").forEach(b=>b.onclick=()=>{tires.splice(tires.findIndex(x=>x.id==b.dataset.rm),1);render()});list.querySelectorAll("[data-k]").forEach(b=>b.onclick=()=>{let t=tires.find(x=>x.id==b.closest(".tire").dataset.id);t.q[b.dataset.k]=b.dataset.v;render()});list.querySelectorAll("input[type=file]").forEach(inp=>inp.onchange=e=>{let f=e.target.files[0];if(!f)return;let t=tires.find(x=>x.id==inp.dataset.id),r=inp.dataset.role;t.files[r]=f;foundSize=foundSize||parseSize(f.name);let rd=new FileReader;rd.onload=ev=>{t.pre[r]=ev.target.result;render()};rd.readAsDataURL(f)})}
async function inline(file,label){busy(label);try{let img=await createImageBitmap(file),mx=1280,sc=Math.min(1,mx/Math.max(img.width,img.height)),c=document.createElement("canvas");c.width=Math.max(1,img.width*sc|0);c.height=Math.max(1,img.height*sc|0);c.getContext("2d").drawImage(img,0,0,c.width,c.height);img.close&&img.close();return{mimeType:"image/jpeg",data:c.toDataURL("image/jpeg",.78).split(",")[1]}}catch(e){return await new Promise((ok,no)=>{let r=new FileReader;r.onload=()=>ok({mimeType:file.type||"image/jpeg",data:String(r.result).split(",")[1]});r.onerror=no;r.readAsDataURL(file)})}}
function missing(){for(let i=0;i<tires.length;i++){let t=tires[i],m=R.filter(r=>!t.files[r]);if(m.length)return`Tire ${i+1}: add ${m.map(ttl).join(", ")}.`;m=Q.filter(([k])=>!t.q[k]);if(m.length)return`Tire ${i+1}: answer ${m.map(x=>x[1]).join(", ")}.`}return""}
$("addTire").onclick=()=>{if(tires.length<4){tires.push(tire());render()}};$("start").onclick=()=>runCheck();$("book").onclick=()=>{let s=(bookTarget&&bookTarget.size)||foundSize;if(!s)toast("Please confirm tire size on FOXI before booking.");location.href=s?`https://www.foxitire.com/?width=${s.width}&profile=${s.profile}&rim=${s.rim}&size=${encodeURIComponent(s.text)}#top-picks`:"https://www.foxitire.com/"};tires.push(tire());render();

function ttl(r){return r=="overall"?"Tire front photo":r=="tread"?"Tire tread photo":"Size and DOT 4-digit code photo"}
function hint(r){return r=="overall"?"Whole tire with wheel":r=="tread"?"Tire tread grooves close-up":"DOT 4-digit code"}
render();

function ttl(r){return r=="overall"?"Tire front photo":r=="tread"?"Tire tread photo":"Size / DOT code photo"}
function hint(r){return r=="overall"?"Whole tire with wheel":r=="tread"?"Tire tread grooves close-up":"4 digits after DOT"}
render();
